# Generated by Django 4.0.3 on 2022-03-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('level', models.IntegerField()),
                ('best_offer_enabled', models.BooleanField(default=False)),
                ('auto_pay_enabled', models.BooleanField(default=False)),
                ('leaf', models.BooleanField(default=False)),
                ('lsd', models.BooleanField(default=False)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
